# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SparseMacArthur',
                'doc_host': 'https://LifeWorks.github.io',
                'git_url': 'https://github.com/LifeWorks/SparseMacArthur',
                'lib_path': 'SparseMacArthur'},
  'syms': {'SparseMacArthur.core': {'SparseMacArthur.core.foo': ('core.html#foo', 'SparseMacArthur/core.py')}}}
